trigger:
  branches:
    include:
    - master
    - topic/*
    - '*/brcrista/*'
    - refs/tags/branch-tag*
    - refs/tags/*-rc

pool: Default

steps:
- bash: |
    echo "Build.SourceBranch=$BUILD_SOURCEBRANCH"
    echo "Build.SourceBranchName=$BUILD_SOURCEBRANCHNAME"
  displayName: 'Check build variables for the branch'
