trigger:
  branches:
    include:
    - master
    - refs/tags/*

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: |
    echo "Build.SourceBranch=$BUILD_SOURCEBRANCH"
    echo "Build.SourceBranchName=$BUILD_SOURCEBRANCHNAME"
  displayName: 'Check build variables for the branch'
